trigger:
  - main  # mainブランチの更新時に実行

pool:
  vmImage: 'ubuntu-latest'  # Linuxエージェントを使用

variables:
  SOURCE_FILE: 'source_file.yml'  # 元のYAMLファイル名
  OUTPUT_FILE: 'replaced_file.yml'  # 出力ファイル名

steps:
  - checkout: self  # GitHubからファイルをチェックアウト

  # 値を受け取って置換処理を実行
  - script: |
      echo "置換を開始します"

      # ファイルのコピーを作成
      cp $(SOURCE_FILE) $(OUTPUT_FILE)

      # ユーザー入力の値を用いて置換
      sed -i "/name: tenant_id/{n;s/value:.*/value: '$(tenant_id)'/}" $(OUTPUT_FILE)
      sed -i "/name: client_secret/{n;s/value:.*/value: '$(client_secret)'/}" $(OUTPUT_FILE)
      sed -i "/name: client_id/{n;s/value:.*/value: '$(client_id)'/}" $(OUTPUT_FILE)
    displayName: 'YAMLファイルの置換'

  # アーティファクトとして保存
  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: '$(OUTPUT_FILE)'
      artifactName: 'ReplacedYAML'
    displayName: '置換後のファイルをアーティファクトとして保存'
