# azure-pipelines.yml
trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

# 変数セクション
variables:
  A: ${{ parameters.a }}  # デフォルト値を空にして、実行時に入力できるようにする
  B: ${{ parameters.b }}

# パラメータの定義
parameters:
  - name: a
    displayName: 'Value for A'
    type: string
    default: '3'  # デフォルト値（任意）
  - name: b
    displayName: 'Value for B'
    type: string
    default: '5'  # デフォルト値（任意）

steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.x'

  - script: |
      python3 -m venv venv
      source venv/bin/activate
    displayName: 'Setup Python environment'

  - script: |
      echo "##vso[task.setvariable variable=A]$(A)"
      echo "##vso[task.setvariable variable=B]$(B)"
      python3 add.py
    env:
      A: $(A)
      B: $(B)
    displayName: 'Run add.py with custom variables'
