
trigger:
  - main  # トリガーを main ブランチの更新に設定

pool:
  vmImage: 'ubuntu-latest'  # Linux エージェントを使用

variables:
  SOURCE_FILE: 'source_file.yml'  # 元ファイルの名前
  OUTPUT_FILE: 'replaced_file.yml'  # 出力する新しいファイル名
  OLD_TEXT: '置換前'  # 置換対象の文字列
  NEW_TEXT: '置換後'  # 置換後の文字列

steps:
  - task: DownloadSecureFile@1  # 必要に応じてセキュアファイルをダウンロード

  - script: |
      # 元ファイルのコピーを作成
      cp $(SOURCE_FILE) $(OUTPUT_FILE)
      # 文字列を置換
      sed -i "s/$(OLD_TEXT)/$(NEW_TEXT)/g" $(OUTPUT_FILE)
    displayName: '文字列置換とファイル出力'
    
  - task: PublishPipelineArtifact@1  # パイプラインの出力として保存
    inputs:
      targetPath: '$(OUTPUT_FILE)'
      artifactName: 'replacedFile'
    displayName: '出力ファイルをアーティファクトとして公開'
