trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  SOURCE_FILE: 'source_file.yml'
  OUTPUT_FILE: 'replaced_file.yml'
  OLD_TEXT: '置換前'
  NEW_TEXT: '置換後'

steps:
  - task: DownloadSecureFile@1
    inputs:
      secureFile: 'source_file.yml'  # セキュアファイルの名前を指定

  - script: |
      cp $(SOURCE_FILE) $(OUTPUT_FILE)
      sed -i "s/$(OLD_TEXT)/$(NEW_TEXT)/g" $(OUTPUT_FILE)
    displayName: '文字列置換とファイル出力'
    
  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: '$(OUTPUT_FILE)'
      artifactName: 'replacedFile'
    displayName: '出力ファイルをアーティファクトとして公開'
