trigger:
  branches:
    include:
      - main  # mainブランチが変更されたときにパイプラインを実行
  paths:
    include:
      - source_file.yml  # source_file.ymlが変更された場合にのみ実行

pool:
  vmImage: 'ubuntu-latest'  # Linuxエージェントを使用

variables:
  - group: ishimaru  # Azure DevOps Libraryで定義したVariable Group名
  - name: SOURCE_FILE
    value: 'source_file.yml'  # 元のYAMLファイル
  - name: OUTPUT_FILE
    value: 'replaced_file.yml'  # 置換後の出力ファイル

steps:
  - checkout: self  # GitHubリポジトリをチェックアウト

  # tenant_id と client_id を抽出
  - script: |
      set -e
      echo "置換対象ファイルから変数を抽出しています..."
      TENANT_ID=$(grep -A 1 'name: tenant_id' ${SOURCE_FILE} | grep 'value:' | awk '{print $2}' | tr -d "'")
      CLIENT_ID=$(grep -A 1 'name: client_id' ${SOURCE_FILE} | grep 'value:' | awk '{print $2}' | tr -d "'")
      echo "抽出された tenant_id: ${TENANT_ID}"
      echo "抽出された client_id: ${CLIENT_ID}"
      # 環境変数として設定
      echo "##vso[task.setvariable variable=tenant_id]${TENANT_ID}"
      echo "##vso[task.setvariable variable=client_id]${CLIENT_ID}"
    displayName: 'tenant_id と client_id を抽出'

  # YAMLファイルの置換処理
  - script: |
      set -e
      echo "YAMLファイルを置換しています..."
      cp ${SOURCE_FILE} ${OUTPUT_FILE}  # 元ファイルをコピー
      sed -i "/name: tenant_id/{n;s/value:.*/value: '${tenant_id}'/}" ${OUTPUT_FILE} || { echo "tenant_id の置換に失敗しました"; exit 1; }
      sed -i "/name: client_secret/{n;s/value:.*/value: '$(client_secret)'/}" ${OUTPUT_FILE} || { echo "client_secret の置換に失敗しました"; exit 1; }
      sed -i "/name: client_id/{n;s/value:.*/value: '${client_id}'/}" ${OUTPUT_FILE} || { echo "client_id の置換に失敗しました"; exit 1; }
      echo "置換後のファイル内容:"
      cat ${OUTPUT_FILE}  # 置換後の内容を表示
    displayName: 'YAMLファイルを置換'

  # 置換後のファイルをartifactとして保存
  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '${OUTPUT_FILE}'  # 置換後のファイル
      ArtifactName: 'replaced-files'  # artifact名
      publishLocation: 'Container'  # Artifactの保存先
    displayName: 'Artifactとして置換後のファイルを保存'
