trigger:
  - main  # mainブランチの更新時に実行

pool:
  vmImage: 'ubuntu-latest'  # Linuxエージェントを使用

variables:
  SOURCE_FILE: 'source_file.yml'  # 元のYAMLファイル名
  OUTPUT_FILE: 'replaced_file.yml'  # 出力ファイル名
  TENANT_ID_VALUE: '置換後のtenant_id'  # tenant_idの置換後の値
  CLIENT_SECRET_VALUE: '置換後のclient_secret'  # client_secretの置換後の値
  CLIENT_ID_VALUE: '置換後のclient_id'  # client_idの置換後の値

steps:
  - checkout: self  # GitHubからファイルをチェックアウト

  - script: |
      # ファイルのコピーを作成
      cp $(SOURCE_FILE) $(OUTPUT_FILE)

      # tenant_idの値を置換
      sed -i "/name: tenant_id/{n;s/value:.*/value: '$(TENANT_ID_VALUE)'/}" $(OUTPUT_FILE)
      
      # client_secretの値を置換
      sed -i "/name: client_secret/{n;s/value:.*/value: '$(CLIENT_SECRET_VALUE)'/}" $(OUTPUT_FILE)

      # client_idの値を置換
      sed -i "/name: client_id/{n;s/value:.*/value: '$(CLIENT_ID_VALUE)'/}" $(OUTPUT_FILE)
    displayName: 'YAMLファイルの値を置換'

  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: '$(OUTPUT_FILE)'
      artifactName: 'ReplacedYAML'
    displayName: '置換後のファイルをアーティファクトとして保存'
