trigger:
  - main  # main ブランチの変更をトリガー

pool:
  vmImage: 'ubuntu-latest'  # Linux エージェントを使用

variables:
  SOURCE_FILE: 'source_file.yml'  # GitHub リポジトリ内のファイル
  OUTPUT_FILE: 'replaced_file.yml'  # 出力する新しいファイル名
  OLD_TEXT: 'test'  # 置換対象の文字列
  NEW_TEXT: '置換成功'  # 置換後の文字列

steps:
  - script: |
      # 元ファイルのコピーを作成
      cp $(SOURCE_FILE) $(OUTPUT_FILE)
      # 文字列を置換
      sed -i "s/$(OLD_TEXT)/$(NEW_TEXT)/g" $(OUTPUT_FILE)
    displayName: '文字列置換とファイル出力'
    
  - task: PublishPipelineArtifact@1  # 置換後のファイルをアーティファクトとして保存
    inputs:
      targetPath: '$(OUTPUT_FILE)'
      artifactName: 'replacedFile'
    displayName: '出力ファイルをアーティファクトとして公開'